spring:
    datasource:
      postgres:
        jdbcUrl: jdbc:postgresql://oliviadb.c5eg88scmjv1.us-east-2.rds.amazonaws.com:5432/oliviaDb
        username: root
        password: Cov.3452
        driver-class-name: org.postgresql.Driver
