spring:
    datasource:
      postgres:
        jdbcUrl: jdbc:postgresql://oliviadb.c5eg88scmjv1.us-east-2.rds.amazonaws.com:5432/oliviaDb
        username: root
        password: Cov.3452
        driver-class-name: org.postgresql.Driver


transbank:
  api-key: 597055555532
  commerce-code: 579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C
  environment: INTEGRATION
  return-url: http://localhost:8080/venta/get/confirmarVenta
